from dotenv import load_dotenv
import os

load_dotenv()

PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY")
PAYSTACK_PUBLIC_KEY = os.getenv("PAYSTACK_PUBLIC_KEY")

RESEND_API_KEY = os.getenv("RESEND_API_KEY")

GOOGLE_SHEET_NAME = os.getenv("GOOGLE_SHEET_NAME")

FRONTEND_URL = os.getenv("FRONTEND_URL")

BOOTH_PRICE = 25000
SERVICE_FEE_RATE = 0.05
MAX_BOOTHS = 10